// console.log('До ошибки');
// let result = 10 / 0;
//
// console.log(result);
//
// let errorTest = undefinedVariable;
//
//
// console.log('После ошибки')

try {
    let result = 10 / 0;
    console.log(result);
     let errorTest = undefinedVariable;
} catch (error) {
   console.log(error.message);
} finally {

}









